### ISSUE TITLE
FadeIn/FadeOut animation not working on Safari (iOS/Mac)

### ISSUE THREAD

**Issue by statm** [MingruiZhang/react-animate-mount#1] opened 2018-07-12 23:46 UTC
The FadeIn / FadeOut component on [demo page](https://mingruizhang.github.io/react-animate-mount/) is not working properly on Safari.

iOS: 11.4
Mac: 10.13.4 with Safari 11.1

**Comment by MingruiZhang** [comment] 2018-07-13 00:46
@statm  Thanks for reporting! The issue is fundamentally related to https://stackoverflow.com/questions/9061520/auto-height-on-parent-container-with-absolute-fixed-children . I am not 100% why the Safari and Chrome behaves differently.

Regardless, its fixed now.

**Closed by MingruiZhang** 2018-07-13 00:46 UTC
